version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/examples"
    schedule:
      interval: "monthly"
    labels: [ ]
    ignore:
      - dependency-name: "*"
