[package]
name = "cubejs-native"
version = "0.28.0"
authors = ["Cube Dev, Inc."]
edition = "2018"
license = "Apache-2.0"
description = "Native module for Cube.js (binding to Rust codebase)"
documentation = "https://cube.dev/docs"
homepage = "https://cube.dev"
exclude = ["index.node"]

[profile.dev]
opt-level = 1

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
cubesqlplanner = { path = "../../rust/cubesqlplanner/cubesqlplanner" }
cubeorchestrator = { path = "../../rust/cubeorchestrator" }
cubenativeutils = { path = "../../rust/cubenativeutils" }
cubesql = { path = "../../rust/cubesql/cubesql" }
anyhow = "1.0"
async-channel = { version = "2" }
async-trait = "0.1.36"
convert_case = "0.6.0"
pin-project = "1.1.5"
findshlibs = "0.10.2"
futures = "0.3.30"
http-body-util = "0.1"
axum = { version = "0.7.5", features = ["default", "ws"] }
libc = "0.2"
log = "0.4.21"
log-reroute = "0.1"
minijinja = { version = "1", features = ["json", "loader"] }
once_cell = "1.10"
# python
pyo3 = { version = "0.20.0", features = [], optional = true }
pyo3-asyncio = { version = "0.20.0", features = ["tokio-runtime", "attributes"], optional = true }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
simple_logger = "1.7.0"
tokio = { version = "1", features = ["full", "rt"] }
uuid = { version = "1", features = ["v4"] }
bytes = "1.5.0"
regex = "1.10.2"

[dependencies.neon]
version = "=1"
default-features = false
features = ["napi-1", "napi-4", "napi-6", "futures"]

[features]
default = ["neon-entrypoint"]
neon-debug = []
neon-entrypoint = []
python = ["pyo3", "pyo3-asyncio"]
