version: '2.2'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 3000:3000
    env_file: .env
    volumes:
      - .:/cube/conf

  curl:
    image: cfmanteiga/alpine-bash-curl-jq
    depends_on:
      - cube
    volumes:
      - .:/curl
    entrypoint: ["sh", "curl/query.sh"]
