name: 'Bird: Release E2E tests ðŸ“¦'
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'latest'
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed
  push:
    paths:
      - '.github/workflows/birdbox.yml'
    branches:
      - 'master'

jobs:
  cli:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-10.15, windows-2019]
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-07-04
          override: true
          components: rustfmt
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore lerna
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            node_modules
            rust/cubestore/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-workspace-main-14.x-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-workspace-main-14.x-
      - name: Set Yarn version
        run: yarn policies set-version v1.22.5
      - name: Yarn install
        run: CUBESTORE_SKIP_POST_INSTALL=true yarn install --frozen-lockfile
      - name: Build client
        run: yarn build
      - name: Lerna tsc
        run: yarn tsc
      - name: Birdbox
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: |
          cd packages/cubejs-testing/
          npx cubejs-cli@${{ github.event.inputs.version }} create birdbox-test-project -d postgres
          export BIRDBOX_CUBEJS_VERSION=${{ github.event.inputs.version }}${{ matrix.node-arch }}
          yarn run dataset:minimal
          yarn run birdbox:cli:postgresql
      - name: Slack Failure
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: oss-ci
          status: FAILED
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  docker:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        target: ['postgresql', 'postgresql-cubestore', 'postgresql-pre-aggregations']
        arch: ['', '-alpine']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-07-04
          override: true
          components: rustfmt
      - name: Install Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Restore lerna
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            node_modules
            rust/cubestore/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-workspace-main-14.x-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-workspace-main-14.x-
      - name: Set Yarn version
        run: yarn policies set-version v1.22.5
      - name: Yarn install
        run: CUBESTORE_SKIP_POST_INSTALL=true yarn install --frozen-lockfile
      - name: Build client
        run: yarn build
      - name: Lerna tsc
        run: yarn tsc
      - name: Birdbox
        run: |
          cd packages/cubejs-testing/
          export DEBUG=testcontainers
          export BIRDBOX_CUBEJS_VERSION=${{ github.event.inputs.version }}${{ matrix.node-arch }}
          yarn run dataset:minimal
          yarn run birdbox:${{ matrix.target }}  
      - name: Slack Failure
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: oss-ci
          status: FAILED
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  docker-cloud:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        target: [ 'athena', 'bigquery' ]
        arch: [ '', '-alpine' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-07-04
          override: true
          components: rustfmt
      - name: Install Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Restore lerna
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            node_modules
            rust/cubestore/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-workspace-main-14.x-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-workspace-main-14.x-
      - name: Set Yarn version
        run: yarn policies set-version v1.22.5
      - name: Yarn install
        run: CUBESTORE_SKIP_POST_INSTALL=true yarn install --frozen-lockfile
      - name: Build client
        run: yarn build
      - name: Lerna tsc
        run: yarn tsc
      - name: Birdbox
        env:
          CUBEJS_DB_BQ_PROJECT_ID: cube-open-source
          CUBEJS_DB_BQ_CREDENTIALS: ${{ secrets.CUBEJS_DB_BQ_CREDENTIALS }}
          CUBEJS_AWS_KEY: ${{ secrets.CUBEJS_AWS_KEY }}
          CUBEJS_AWS_SECRET: ${{ secrets.CUBEJS_AWS_SECRET }}
          CUBEJS_AWS_REGION: us-east-1
          CUBEJS_AWS_S3_OUTPUT_LOCATION: s3://cubejs-opensource/testing/output
        run: |
          cd packages/cubejs-testing/
          export DEBUG=testcontainers
          export BIRDBOX_CUBEJS_VERSION=${{ github.event.inputs.version }}${{ matrix.node-arch }}
          case ${{ matrix.target }} == 'athena' ]] in
            athena)
              export CUBEJS_AWS_REGION=us-east-1
              export CUBEJS_AWS_S3_OUTPUT_LOCATION=s3://cubejs-opensource/testing/output
              export CUBEJS_DB_EXPORT_BUCKET=s3://cubejs-opensource/testing/export
              ;;
            bigquery)
              export CUBEJS_DB_BQ_PROJECT_ID=cube-open-source
              export CUBEJS_DB_EXPORT_BUCKET=cube-open-source-export-bucket
              ;;
          esac
          yarn run birdbox:${{ matrix.target }} --mode=docker
      - name: Slack Failure
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: oss-ci
          status: FAILED
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  cypress:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
        include:
          - browser: chrome
            os: ubuntu-20.04
            container: cypress/browsers:node12.18.3-chrome89-ff86
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-07-04
          override: true
          components: rustfmt
      - name: Install Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Restore lerna
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            node_modules
            rust/cubestore/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-workspace-main-14.x-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-workspace-main-14.x-
      - name: Set Yarn version
        run: yarn policies set-version v1.22.5
      - name: Yarn install
        run: CUBESTORE_SKIP_POST_INSTALL=true yarn install --frozen-lockfile
      - name: Lerna tsc
        run: yarn tsc
      - name: Birdbox
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: |
          cd packages/cubejs-testing/
          export DEBUG=testcontainers
          export BIRDBOX_CYPRESS_BROWSER=${{ matrix.browser }}
          export BIRDBOX_CUBEJS_VERSION=${{ github.event.inputs.version }}
          yarn run cypress:install
          yarn run dataset:minimal
          yarn run cypress:birdbox
      - name: Slack Failure
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: oss-ci
          status: FAILED
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
