name: Guides

on:
  push:
    paths:
      - '.github/workflows/guides.yml'
      - '.github/actions/deploy-guide.sh'
      - 'guides/**'
    branches:
      - master

jobs:

  angular-dashboard:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: pheel/path-watcher-action@v1
        id: modified
        with:
          paths: '.github/workflows/guides.yml,.github/actions/deploy-guide.sh,guides/angular-dashboard/**'

      - if: steps.modified.outputs.modified
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - if: steps.modified.outputs.modified
        run: .github/actions/deploy-guide.sh
        env:
          GUIDE_SLUG: angular-dashboard
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  d3-dashboard:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: pheel/path-watcher-action@v1
        id: modified
        with:
          paths: '.github/workflows/guides.yml,.github/actions/deploy-guide.sh,guides/d3-dashboard/**'

      - if: steps.modified.outputs.modified
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - if: steps.modified.outputs.modified
        run: .github/actions/deploy-guide.sh
        env:
          GUIDE_SLUG: d3-dashboard
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  clickhouse-dashboard:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: pheel/path-watcher-action@v1
        id: modified
        with:
          paths: '.github/workflows/guides.yml,.github/actions/deploy-guide.sh,guides/clickhouse-dashboard/**'

      - if: steps.modified.outputs.modified
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - if: steps.modified.outputs.modified
        run: .github/actions/deploy-guide.sh
        env:
          GUIDE_SLUG: clickhouse-dashboard
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  mapbox:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: pheel/path-watcher-action@v1
        id: modified
        with:
          paths: '.github/workflows/guides.yml,.github/actions/deploy-guide.sh,guides/mapbox/**'

      - if: steps.modified.outputs.modified
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - if: steps.modified.outputs.modified
        run: .github/actions/deploy-guide.sh
        env:
          GUIDE_SLUG: mapbox
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  material-ui-dashboard:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: pheel/path-watcher-action@v1
        id: modified
        with:
          paths: '.github/workflows/guides.yml,.github/actions/deploy-guide.sh,guides/material-ui-dashboard/**'

      - if: steps.modified.outputs.modified
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - if: steps.modified.outputs.modified
        run: .github/actions/deploy-guide.sh
        env:
          GUIDE_SLUG: material-ui-dashboard
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  react-dashboard:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: pheel/path-watcher-action@v1
        id: modified
        with:
          paths: '.github/workflows/guides.yml,.github/actions/deploy-guide.sh,guides/react-dashboard/**'

      - if: steps.modified.outputs.modified
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - if: steps.modified.outputs.modified
        run: .github/actions/deploy-guide.sh
        env:
          GUIDE_SLUG: react-dashboard
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  real-time-dashboard:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: pheel/path-watcher-action@v1
        id: modified
        with:
          paths: '.github/workflows/guides.yml,.github/actions/deploy-guide.sh,guides/real-time-dashboard/**'

      - if: steps.modified.outputs.modified
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - if: steps.modified.outputs.modified
        run: .github/actions/deploy-guide.sh
        env:
          GUIDE_SLUG: real-time-dashboard
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  web-analytics:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: pheel/path-watcher-action@v1
        id: modified
        with:
          paths: '.github/workflows/guides.yml,.github/actions/deploy-guide.sh,guides/web-analytics/**'

      - if: steps.modified.outputs.modified
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - if: steps.modified.outputs.modified
        run: .github/actions/deploy-guide.sh
        env:
          GUIDE_SLUG: web-analytics
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
